# Generated by Django 4.2.11 on 2024-03-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0011_alter_actualuploadmonthlyfigure_financial_code_and_more"),
        (
            "previous_years",
            "0005_alter_archivedactualuploadmonthlyfigure_financial_code_and_more",
        ),
        ("upload_split_file", "0003_auto_20211213_1837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paysplitcoefficient",
            name="financial_code_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_%(app_label)s_%(class)ss",
                to="forecast.financialcode",
            ),
        ),
        migrations.AlterField(
            model_name="paysplitcoefficient",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="previousyearpaysplitcoefficient",
            name="financial_code_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="previous_years.archivedfinancialcode",
            ),
        ),
        migrations.AlterField(
            model_name="previousyearpaysplitcoefficient",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="splitpayactualfigure",
            name="financial_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialcode",
            ),
        ),
        migrations.AlterField(
            model_name="splitpayactualfigure",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="uploadpaysplitcoefficient",
            name="financial_code_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="to_%(app_label)s_%(class)ss",
                to="forecast.financialcode",
            ),
        ),
        migrations.AlterField(
            model_name="uploadpaysplitcoefficient",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
    ]
