# Generated by Django 3.2.4 on 2021-08-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210316_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(blank=True,
                                   max_length=150,
                                   verbose_name='first name'),   # /PS-IGNORE
        ),
    ]
