# Generated by Django 3.2.13 on 2022-04-27 10:46

from django.apps import apps
from django.contrib.auth.management import create_permissions
from django.db import migrations

Permission = apps.get_model("auth", "Permission")
Group = apps.get_model("auth", "Group")


def add_all_permissions():
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


def assign_permissions(group, permission_codenames):
    for permission_codename in permission_codenames:
        permission = Permission.objects.get(
            codename=permission_codename,
        )
        group.permissions.add(
            permission,
        )


def add_future_edit_permissions(apps, schema_editor):
    add_all_permissions()
    # Finance admins
    finance_adminstrators, _ = Group.objects.get_or_create(
        name="Finance Administrator",
    )
    assign_permissions(
        finance_adminstrators,
        [
            # admin permissions follow
            "can_set_future_edit_lock",
            "can_edit_future_whilst_closed",
        ],
    )

    # Finance Business Partners
    finance_business_partners, _ = Group.objects.get_or_create(
        name="Finance Business Partner/BSCE",
    )
    assign_permissions(
        finance_business_partners,
        [
            "can_edit_future_whilst_closed",
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_historicaluser_first_name"),
    ]

    operations = [
        migrations.RunPython(add_future_edit_permissions),
    ]
