# Generated by Django 4.2.15 on 2024-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20220427_1046"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalgroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical group",
                "verbose_name_plural": "historical groups",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalpermission",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical permission",
                "verbose_name_plural": "historical permissions",
            },
        ),
        migrations.AlterModelOptions(
            name="historicaluser",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical user",
                "verbose_name_plural": "historical users",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorycommandlog",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical command log",
                "verbose_name_plural": "historical command logs",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryfinancialyear",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical financial year",
                "verbose_name_plural": "historical financial years",
            },
        ),
        migrations.AlterField(
            model_name="historicalgroup",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicalpermission",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorycommandlog",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryfinancialyear",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
