# Generated by Django 4.2.16 on 2024-12-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_historicalgroup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayUplift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apr", models.FloatField(default=1.0)),
                ("may", models.FloatField(default=1.0)),
                ("jun", models.FloatField(default=1.0)),
                ("jul", models.FloatField(default=1.0)),
                ("aug", models.FloatField(default=1.0)),
                ("sep", models.FloatField(default=1.0)),
                ("oct", models.FloatField(default=1.0)),
                ("nov", models.FloatField(default=1.0)),
                ("dec", models.FloatField(default=1.0)),
                ("jan", models.FloatField(default=1.0)),
                ("feb", models.FloatField(default=1.0)),
                ("mar", models.FloatField(default=1.0)),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.financialyear",
                    ),
                ),
            ],
        ),
    ]
