# Generated by Django 5.1.3 on 2024-12-09 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_payuplift"),
        ("costcentre", "0008_alter_simplehistoryarchivedcostcentre_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attrition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apr", models.FloatField(default=1.0)),
                ("may", models.FloatField(default=1.0)),
                ("jun", models.FloatField(default=1.0)),
                ("jul", models.FloatField(default=1.0)),
                ("aug", models.FloatField(default=1.0)),
                ("sep", models.FloatField(default=1.0)),
                ("oct", models.FloatField(default=1.0)),
                ("nov", models.FloatField(default=1.0)),
                ("dec", models.FloatField(default=1.0)),
                ("jan", models.FloatField(default=1.0)),
                ("feb", models.FloatField(default=1.0)),
                ("mar", models.FloatField(default=1.0)),
                (
                    "cost_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="costcentre.costcentre",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.financialyear",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
