# Generated by Django 5.1.3 on 2024-12-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_attrition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attrition",
            options={"verbose_name_plural": "attrition"},
        ),
    ]
