# Generated by Django 5.1.3 on 2024-12-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_attrition_options"),
        ("costcentre", "0008_alter_simplehistoryarchivedcostcentre_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attrition",
            name="cost_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="costcentre.costcentre",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="attrition",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.financialyear",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="payuplift",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.financialyear",
                unique=True,
            ),
        ),
    ]
