# Generated by Django 5.1.3 on 2024-12-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_attrition_cost_centre_and_more"),
        ("costcentre", "0008_alter_simplehistoryarchivedcostcentre_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attrition",
            name="cost_centre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="costcentre.costcentre",
            ),
        ),
        migrations.AlterField(
            model_name="attrition",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.financialyear"
            ),
        ),
        migrations.AlterField(
            model_name="payuplift",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.financialyear"
            ),
        ),
        migrations.AddConstraint(
            model_name="attrition",
            constraint=models.UniqueConstraint(
                fields=("financial_year", "cost_centre"), name="unique_attrition"
            ),
        ),
        migrations.AddConstraint(
            model_name="payuplift",
            constraint=models.UniqueConstraint(
                fields=("financial_year",), name="unique_pay_uplift"
            ),
        ),
    ]
