# Generated by Django 5.1.3 on 2024-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_attrition_cost_centre_and_more"),
        ("costcentre", "0008_alter_simplehistoryarchivedcostcentre_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="attrition",
            name="unique_attrition",
        ),
        migrations.AddConstraint(
            model_name="attrition",
            constraint=models.UniqueConstraint(
                fields=("financial_year", "cost_centre"),
                name="unique_attrition",
                nulls_distinct=False,
            ),
        ),
    ]
