# Generated by Django 5.1.5 on 2025-03-12 16:17

from django.db import migrations


def update_periods(apps, schema_editor):
    Attrition = apps.get_model("core", "Attrition")
    PayUplift = apps.get_model("core", "PayUplift")
    for model in (Attrition, PayUplift):
        for obj in model.objects.all():
            obj.apr = round(obj.apr - 1.0, 4)
            obj.may = round(obj.may - 1.0, 4)
            obj.jun = round(obj.jun - 1.0, 4)
            obj.jul = round(obj.jul - 1.0, 4)
            obj.aug = round(obj.aug - 1.0, 4)
            obj.sep = round(obj.sep - 1.0, 4)
            obj.oct = round(obj.oct - 1.0, 4)
            obj.nov = round(obj.nov - 1.0, 4)
            obj.dec = round(obj.dec - 1.0, 4)
            obj.jan = round(obj.jan - 1.0, 4)
            obj.feb = round(obj.feb - 1.0, 4)
            obj.mar = round(obj.mar - 1.0, 4)
            obj.save()


def reverse_periods(apps, schema_editor):
    Attrition = apps.get_model("core", "Attrition")
    PayUplift = apps.get_model("core", "PayUplift")
    for model in (Attrition, PayUplift):
        for obj in model.objects.all():
            obj.apr = obj.apr + 1.0
            obj.may = obj.may + 1.0
            obj.jun = obj.jun + 1.0
            obj.jul = obj.jul + 1.0
            obj.aug = obj.aug + 1.0
            obj.sep = obj.sep + 1.0
            obj.oct = obj.oct + 1.0
            obj.nov = obj.nov + 1.0
            obj.dec = obj.dec + 1.0
            obj.jan = obj.jan + 1.0
            obj.feb = obj.feb + 1.0
            obj.mar = obj.mar + 1.0
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_alter_attrition_apr_alter_attrition_aug_and_more"),
    ]

    operations = [migrations.RunPython(update_periods, reverse_code=reverse_periods)]
