# Generated by Django 3.2.13 on 2022-07-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloadsupport', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadLog',
        ),
        migrations.DeleteModel(
            name='SimpleHistoryDownloadLog',
        ),
    ]
