version: 2.1

  job_defaults: &job_defaults
    parameters:
      python_image:
        type: string

      postgres_image:
        type: string

      publish_coverage:
        type: boolean
        default: false

    environment:
      DATABASE_URL: postgresql://postgres@localhost/fido
      ICMS_DEBUG: 'True'
      DJANGO_SECRET_KEY: test
      DJANGO_SETTINGS_MODULE: fido.settings.dev

    working_directory: ~/

    docker:
      - image: <<parameters.python_image>>
      - image: <<parameters.postgres_image>>
        environment:
          POSTGRES_DB=fido

    steps:
      - checkout

#      - restore_cache:
#          name: Restore pip cache
#          keys:
#            - v1-icms-{{ checksum "Pipfile.lock" }}
#            - v1-icms-
#          paths:
#            - ~/cache/pip

      - run:
          name: Install Python dependencies
          command: pip install

      - run:
          name: Install JS dependencies
          command: npm install

#      - save_cache:
#          name: Save pip cache
#          key: v1-icms-{{ checksum "Pipfile.lock" }}
#          paths:
#            - ~/cache/pip

      - run:
          name: Run tests
          command: python manage.py test

      - run:
          name: Run Flake8
          command: python -m flake8

      - store_test_results:
          path: test-reports

      - when:
          condition: <<parameters.publish_coverage>>
          steps:
            - run:
                name: Publish coverage
                command: |
                  wget -O codecov.sh https://codecov.io/bash
                  bash ./codecov.sh -t ${COV_TOKEN}
  jobs:
    build:
      <<: *job_defaults

  workflows:
    version: 2

    # Current standard environment
    Default build:
      jobs:
        - build:
            publish_coverage: true
            python_image: python:3.6.6-node
            postgres_image: postgres:10.7
