# Generated by Django 4.2.15 on 2024-10-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chartofaccountDIT", "0015_alter_simplehistoryanalysis1_options_and_more"),
        ("core", "0013_alter_historicalgroup_options_and_more"),
        ("costcentre", "0008_alter_simplehistoryarchivedcostcentre_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_no", models.CharField(max_length=8, unique=True)),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                (
                    "cost_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="costcentre.costcentre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_1", models.BooleanField(default=True)),
                ("period_2", models.BooleanField(default=True)),
                ("period_3", models.BooleanField(default=True)),
                ("period_4", models.BooleanField(default=True)),
                ("period_5", models.BooleanField(default=True)),
                ("period_6", models.BooleanField(default=True)),
                ("period_7", models.BooleanField(default=True)),
                ("period_8", models.BooleanField(default=True)),
                ("period_9", models.BooleanField(default=True)),
                ("period_10", models.BooleanField(default=True)),
                ("period_11", models.BooleanField(default=True)),
                ("period_12", models.BooleanField(default=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecast",
                        to="staff.staff",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.financialyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debit_amount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("credit_amount", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "pay_element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="staff.payelement",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="staff.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayElementGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "natural_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.naturalcode",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payelement",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="staff.payelementgroup"
            ),
        ),
        migrations.AddField(
            model_name="payelement",
            name="natural_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="chartofaccountDIT.naturalcode",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffforecast",
            constraint=models.UniqueConstraint(
                fields=("staff", "year"), name="unique_staff_forecast"
            ),
        ),
    ]
