# Generated by Django 3.2.13 on 2022-08-19 13:35

from django.db import migrations

# Create in FFT tables that will be created in data lake by the pipelines
# Needed for testing before creating the pipelines
drop_sql = """
DROP VIEW IF EXISTS dw_current_year_data;

DROP VIEW IF EXISTS dw_actual_forecast_ytd;
DROP VIEW IF EXISTS dw_actual_ytd;
DROP VIEW IF EXISTS dw_current_rates;
DROP VIEW IF EXISTS dw_current_year_outturn;

DROP TABLE IF EXISTS public.dw_simulation_mi_report_forecast_actual;
DROP TABLE IF EXISTS public.dw_simulation_mi_report_budget;
DROP TABLE IF EXISTS dw_simulation_mi_report_previous_year_actual;
DROP TABLE IF EXISTS dw_simulation_mi_report_previous_year_actual;
DROP TABLE IF EXISTS dw_simulation_mi_report_previous_year_actual;

"""

create_sql = """
CREATE TABLE IF NOT EXISTS  dw_simulation_mi_report_forecast_actual
(
    cost_centre_code character varying(6),
    actual_nac integer,
    programme_code character varying(50),
    contract_code character varying,
    market_code character varying,
    project_code character varying,
    expenditure_type character varying(100),
    expenditure_type_description character varying(100),
    financial_code integer,
    actual numeric,
    forecast numeric,
    actual_loaded boolean, 
    financial_period_code integer,
    financial_period_name character varying(10),
    archived_financial_period_code integer,
    archived_financial_period_name character varying(10),
    financial_year integer,
    archiving_year integer
);

CREATE TABLE IF NOT EXISTS public.dw_simulation_mi_report_budget
(
    cost_centre_code character varying(6),
    actual_nac integer,
    programme_code character varying(50),
    contract_code character varying,
    market_code character varying,
    project_code character varying,
    expenditure_type character varying(100),
    expenditure_type_description character varying(100),
    financial_code integer,
    budget numeric,
    financial_period_code integer,
    financial_period_name character varying(10),
    archived_financial_period_code integer,
    archived_financial_period_name character varying(10),
    financial_year integer,
    archiving_year integer
);


CREATE TABLE IF NOT EXISTS public.dw_simulation_mi_report_previous_year_actual
(
    cost_centre_code character varying(6),
    actual_nac integer,
    programme_code character varying(50),    
    market_code character varying,
    contract_code character varying,
    project_code character varying,
    expenditure_type character varying(100),
    expenditure_type_description character varying(100),
    financial_code integer,
    previous_year_actual numeric,
    financial_period_code integer,
    financial_period_name character varying(10),
    archived_financial_period_code integer,
    archived_financial_period_name character varying(10),
    financial_year integer,
    archiving_year integer
);


CREATE VIEW dw_current_year_outturn as 
SELECT financial_code, coalesce(sum(actual+forecast), 0)  as current_year_outturn, archived_financial_period_code
	FROM public.dw_simulation_mi_report_forecast_actual
	GROUP BY financial_code, archived_financial_period_code;


	
CREATE VIEW dw_actual_forecast_ytd as	
SELECT financial_code, financial_period_code, archived_financial_period_code, 
sum(COALESCE(forecast, 0) + coalesce(actual, 0))  
OVER (PARTITION BY financial_code, archived_financial_period_code ORDER BY financial_period_code)
AS ytd_forecast_actual
	FROM public.dw_simulation_mi_report_forecast_actual;
	

CREATE VIEW dw_actual_ytd as
SELECT financial_code, financial_period_code, archived_financial_period_code, sum(coalesce(actual, 0)) 
OVER (PARTITION BY financial_code, archived_financial_period_code ORDER BY financial_period_code)
AS ytd_actual
	FROM public.dw_simulation_mi_report_forecast_actual
	WHERE financial_period_code <= archived_financial_period_code;
	

CREATE VIEW dw_current_rates as
    SELECT financial_code, financial_period_code, archived_financial_period_code, 
    sum(coalesce(actual, 0))  OVER ( PARTITION BY financial_code, archived_financial_period_code ORDER BY financial_period_code) as run_rate_ytd,
    avg(coalesce(actual, 0)) OVER (PARTITION BY financial_code, archived_financial_period_code ORDER BY financial_period_code) * 12 as full_year_run_rate
        FROM dw_simulation_mi_report_forecast_actual WHERE financial_period_code < archived_financial_period_code 
        or (financial_period_code = archived_financial_period_code AND actual_loaded = true)
    
    UNION				 
    
     SELECT fa.financial_code, fa.financial_period_code, fa.archived_financial_period_code, 
    
    rate.ytd_run_rate * financial_period_code as run_rate_ytd,
    rate.ytd_run_rate * 12 as full_year_run_rate
        FROM dw_simulation_mi_report_forecast_actual fa INNER JOIN 
        (select avg(COALESCE(actual, 0)) as ytd_run_rate, financial_code, archived_financial_period_code
				FROM dw_simulation_mi_report_forecast_actual WHERE actual_loaded = true
				group by financial_code, archived_financial_period_code) as rate ON rate.financial_code = fa.financial_code and rate.archived_financial_period_code = fa.archived_financial_period_code
            
        WHERE fa.financial_period_code > fa.archived_financial_period_code 
        or (fa.financial_period_code = fa.archived_financial_period_code AND actual_loaded = false);

	

CREATE VIEW dw_current_year_data as
SELECT 
       COALESCE(b.financial_code, f.financial_code) as financial_code, 
	   COALESCE(b.cost_centre_code, f.cost_centre_code) as cost_centre_code,
       COALESCE(b.actual_nac,f.actual_nac) as actual_nac, 
       COALESCE(b.programme_code, f.programme_code) as programme_code, 
       COALESCE(b.contract_code, f.contract_code) as contract_code, 
       COALESCE(b.market_code, f.market_code) as market_code, 
       COALESCE(b.project_code, f.project_code) as project_code, 
       COALESCE(b.expenditure_type, f.expenditure_type) as expenditure_type, 
       COALESCE(b.expenditure_type_description, f.expenditure_type_description) as expenditure_type_description, 
       COALESCE(b.budget, 0) period_budget, 
	   COALESCE(f.actual, 0) as period_actual,
	   COALESCE(f.forecast, 0) as period_forecast,
       COALESCE(b.financial_period_code, f.financial_period_code) as financial_period_code, 
       COALESCE(b.financial_period_name, f.financial_period_name) as financial_period_name, 
       COALESCE(b.archived_financial_period_code, f.archived_financial_period_code) as archived_financial_period_code, 
       COALESCE(b.archived_financial_period_name, f.archived_financial_period_name) as archived_financial_period_name, 
       COALESCE(b.financial_year, f.financial_year) as financial_year, 
       COALESCE(b.archiving_year,f.archiving_year) as archiving_year,	   
	   (COALESCE(f.actual, 0) + COALESCE(f.forecast, 0)) as period_actual_forecast,	
	   (COALESCE(b.budget, 0) - (COALESCE(f.actual, 0) + COALESCE(f.forecast, 0))) as period_actual_forecast_budget_variance,
       COALESCE(b.ytd_budget, 0) as ytd_budget,
 	   COALESCE(a_ytd.ytd_actual, 0) as ytd_actual,
 	   COALESCE(fa_ytd.ytd_forecast_actual, 0) as ytd_actual_forecast,
 	   (COALESCE(b.ytd_budget, 0) - COALESCE(fa_ytd.ytd_forecast_actual, 0)) as ytd_actual_forecast_budget_variance,
	   COALESCE(b.budget_outturn, 0) as full_year_budget,
 	   COALESCE(cy_o.current_year_outturn, 0) as full_year_actual_forecast,
 	   (COALESCE(cy_o.current_year_outturn, 0) - COALESCE(b.budget_outturn, 0)) as full_year_actual_forecast_budget_variance,
 	   COALESCE(rates.run_rate_ytd, 0) as ytd_run_rate,
  	   COALESCE(rates.full_year_run_rate, 0) as full_year_run_rate,
	   COALESCE(fp.forecast, 0) as previous_period_forecast 
	FROM (dw_simulation_mi_report_forecast_actual f
	full outer join dw_budget_data b 
	on b.financial_code = f.financial_code 
			AND b.archived_financial_period_code = f.archived_financial_period_code 
		  	AND f.financial_period_code = b.financial_period_code and b.financial_year = f.financial_year) 
		  JOIN dw_current_year_outturn cy_o ON cy_o.financial_code = f.financial_code AND cy_o.archived_financial_period_code = f.archived_financial_period_code
 		  JOIN dw_actual_forecast_ytd fa_ytd ON fa_ytd.financial_code = f.financial_code 
 		  			AND fa_ytd.archived_financial_period_code = f.archived_financial_period_code 
 					AND fa_ytd.financial_period_code = f.financial_period_code
 		  LEFT OUTER JOIN dw_actual_ytd a_ytd ON a_ytd.financial_code = f.financial_code 
 		  			AND a_ytd.archived_financial_period_code = f.archived_financial_period_code 
 					AND a_ytd.financial_period_code = f.financial_period_code
 		  JOIN dw_current_rates rates ON rates.financial_code = f.financial_code 
 					AND rates.financial_period_code = f.financial_period_code
 		  			AND rates.archived_financial_period_code = f.archived_financial_period_code
	LEFT OUTER JOIN (
	SELECT financial_code, forecast, financial_period_code, archived_financial_period_code
	FROM public.dw_simulation_mi_report_forecast_actual fp
	) fp on fp.financial_code = f.financial_code AND fp.financial_period_code = f.financial_period_code AND fp.archived_financial_period_code = f.archived_financial_period_code - 1
	;

"""


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            f"{drop_sql} {create_sql}",
            drop_sql,
        ),
    ]
