# Generated by Django 3.2.13 on 2022-08-31 12:23

from django.db import migrations

drop_sql = """
DROP VIEW IF EXISTS dw_previous_year_data;
DROP VIEW IF EXISTS dw_prev_year_outturn;
DROP VIEW IF EXISTS dw_previous_year_ytd;
"""


create_sql= """

	    
CREATE VIEW dw_prev_year_outturn as
SELECT financial_code, sum(previous_year_actual) as previous_year_outturn
	FROM public.dw_simulation_mi_report_previous_year_actual
	group by financial_code;

CREATE VIEW dw_previous_year_ytd as
SELECT financial_code, financial_period_code,  
sum(previous_year_actual) OVER (PARTITION BY financial_code ORDER by financial_period_code) as previous_year_ytd
	FROM public.dw_simulation_mi_report_previous_year_actual;
	    
CREATE VIEW dw_previous_year_data as 
        SELECT  
        pa.cost_centre_code, pa.actual_nac, pa.programme_code, 
        pa.contract_code, pa.market_code, pa.project_code, pa.expenditure_type, pa.expenditure_type_description, 
        pa.previous_year_actual as previous_year_period_actual, 
        pa_o.previous_year_outturn, 
        pa.financial_period_code,
        pa.financial_period_name, 
        pa_ytd.previous_year_ytd,
        per.financial_period_code as archived_financial_period_code,
        per.period_short_name as archived_financial_period_name,
        pa.financial_year,
        pa.archiving_year
        
            FROM public.dw_simulation_mi_report_previous_year_actual pa
            inner join dw_prev_year_outturn pa_o on pa_o.financial_code = pa.financial_code
            inner join dw_previous_year_ytd pa_ytd on pa_ytd.financial_code = pa.financial_code 
            AND pa.financial_period_code = pa_ytd.financial_period_code
            CROSS JOIN dw_simulation_financial_period_in_use per;    	    

	    
	    
	    """


class Migration(migrations.Migration):

    dependencies = [
        ('dw_simulation', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            f"{drop_sql} {create_sql}",
            drop_sql,
        ),
    ]
