# Generated by Django 3.2.13 on 2022-09-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dw_simulation', '0003_budget'),
    ]

    operations = [
    ]
