# Generated by Django 3.2.15 on 2022-09-12 15:27

from django.db import migrations

drop_sql = """
    DROP TABLE IF  EXISTS  dw_simulation_mi_report_future_year_forecast;
    DROP TABLE IF  EXISTS  dw_simulation_mi_report_future_year_budget;      
"""

create_sql = """
CREATE TABLE IF NOT EXISTS  dw_simulation_mi_report_future_year_forecast
(
    cost_centre_code character varying(6),
    actual_nac integer,
    programme_code character varying(50),
    contract_code character varying,
    market_code character varying,
    project_code character varying,
    expenditure_type character varying(100),
    expenditure_type_description character varying(100),
    financial_code integer,
    future_forecast numeric,
    actual_loaded boolean, 
    financial_period_code integer,
    financial_period_name character varying(10),
    archived_financial_period_code integer,
    archived_financial_period_name character varying(10),
    financial_year integer,
    archiving_year integer
);

CREATE TABLE IF NOT EXISTS  dw_simulation_mi_report_future_year_budget
(
    cost_centre_code character varying(6),
    actual_nac integer,
    programme_code character varying(50),
    contract_code character varying,
    market_code character varying,
    project_code character varying,
    expenditure_type character varying(100),
    expenditure_type_description character varying(100),
    financial_code integer,
    future_budget numeric,
    actual_loaded boolean, 
    financial_period_code integer,
    financial_period_name character varying(10),
    archived_financial_period_code integer,
    archived_financial_period_name character varying(10),
    financial_year integer,
    archiving_year integer
);

"""


class Migration(migrations.Migration):

    dependencies = [
        ('dw_simulation', '0004_full_data'),
    ]

    operations = [
        migrations.RunSQL(
            f"{drop_sql} {create_sql}",
            drop_sql,
        ),
    ]
