version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.04.2
      docker_layer_caching: true

    steps:
      - checkout
      - run: mkdir test-reports
      - run: cp .env.ci .env
      - run:
          name: Build images
          command: make build
      - run:
          name: Run containers
          command: make up-detatched
      - run:
          name: Install npm packages
          command: npm ci
      - run:
          name: Run postinstall script
          command: npm run postinstall
      - run:
          name: Collect static
          command: make collectstatic
      - run:
          name: Run Flake8
          command: make flake8
      - run:
          name: Run isort
          command: make isort-check
      - run:
          name: Run black
          command: make black-check
      - run:
          name: Run tests
          command: make pytest
      - run:
          name: Run BDD tests
          command: make bdd

      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
