version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers-legacy
        environment:
          FLASK_CONFIG: testing
          DATABASE_URL: psql://ubuntu@localhost:5432/fido_test
          DJANGO_SETTINGS_MODULE: fido.settings.test
          SECRET_KEY: used_for_testing
          ALLOWED_HOSTS: "*"

      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: fido_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
#      - restore_cache:
#          key: deps2-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Python deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/test.txt
#      - save_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
#          paths:
#            - "venv"
      - run:
          name: Install React app
          command:
            npm install
#      - save_cache:
#          key: deps2-{{ .Branch }}-{{ checksum "package.json" }}
#          paths:
#            - ./
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python manage.py test
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python behave
      - run:
          name: Run Flake8
          command: |
            . venv/bin/activate
            python -m flake8

      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
