version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-node-browsers-legacy
        environment:
          FLASK_CONFIG: testing
          TEST_DATABASE_URL: psql://ubuntu@localhost:5432/fido_test?sslmode=disable

      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: fido_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: |
            java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Python deps
          command:
            pip install -r requirements/test.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/test.txt" }}
          paths:
            - /app
      - run:
          name: Install React app
          command:
            npm install
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - /app
      - run:
          name: Run tests
          command: python manage.py test
      - run:
          name: Run tests
          command: python behave
      - run:
          name: Run Flake8
          command: python -m flake8

      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
