version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.5 # /PS-IGNORE
jobs:
  build:
    # docker:
    #   - image: cimg/python:3.9-browsers
    #     environment:
    #       FLASK_CONFIG: testing
    #       DATABASE_URL: psql://ubuntu@localhost:5432/fido_test
    #       DJANGO_SETTINGS_MODULE: config.settings.ci
    #       SECRET_KEY: used_for_testing
    #       ALLOWED_HOSTS: "*"
    #       SELENIUM_ADDRESS: localhost
    #       SELENIUM_HOST: localhost
    #       USE_SELENIUM_HUB: False
    #   - image: circleci/postgres:11-alpine-ram
    #     environment:
    #       POSTGRES_USER: ubuntu
    #       POSTGRES_DB: fido_test
    #       POSTGRES_PASSWORD: ""
    machine:
      image: ubuntu-2204:2023.04.2
      docker_layer_caching: true

    steps:
      # - browser-tools/install-browser-tools
      - checkout
      - run: mkdir test-reports
      - run: touch .env
      # - run:
      #     name: Download Selenium
      #     command: |
      #       curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run:
      #     name: Start Selenium
      #     command: |
      #       java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
      #     background: true
      - run:
          name: Build images
          command: make build
      - run:
          name: Install latest NPM
          command: npm install npm
      - run:
          name: Install React app
          command: npm install
      - run:
          name: Collect static
          command: make collectstatic
      - run:
          name: Compile CSS
          command: make compilescss
      - run:
          name: Run tests
          command: make pytest
      - run:
          name: Run BDD tests
          command: make bdd
      - run:
          name: Run Flake8
          command: make flake8
      - run:
          name: Run isort
          command: make isort-check
      - run:
          name: Run black
          command: make black-check

      - store_artifacts:
          path: test-reports/
          destination: tr1
      - store_test_results:
          path: test-reports/
