# Generated by Django 3.0.3 on 2021-02-23 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecast', '0004_auto_20200820_0751'),
        ('previous_years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleHistoryArchivedActualUploadMonthlyFigure',
            fields=[
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('financial_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='previous_years.ArchivedFinancialCode')),
                ('financial_period', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.FinancialYear')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical archived actual upload monthly figure',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ArchivedActualUploadMonthlyFigure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_years_archivedactualuploadmonthlyfigures', to='previous_years.ArchivedFinancialCode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='previous_years_archivedactualuploadmonthlyfigures', to='forecast.FinancialPeriod')),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FinancialYear')),
            ],
        ),
        migrations.AddConstraint(
            model_name='archivedactualuploadmonthlyfigure',
            constraint=models.UniqueConstraint(fields=('financial_code', 'financial_year', 'financial_period'), name='ArchivedActualUploadMonthlyFigure_unique1'),
        ),
    ]
