# Generated by Django 3.2.4 on 2021-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("previous_years", "0003_auto_20210224_0749"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedforecastdata",
            name="previous_outturn",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="archivedforecastdataupload",
            name="previous_outturn",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="simplehistoryarchivedforecastdata",
            name="previous_outturn",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="simplehistoryarchivedforecastdataupload",
            name="previous_outturn",
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
