# Generated by Django 4.2.11 on 2024-03-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20220427_1046"),
        ("forecast", "0011_alter_actualuploadmonthlyfigure_financial_code_and_more"),
        ("previous_years", "0004_auto_20210707_1008"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedactualuploadmonthlyfigure",
            name="financial_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="previous_years.archivedfinancialcode",
            ),
        ),
        migrations.AlterField(
            model_name="archivedactualuploadmonthlyfigure",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="archivedfinancialcode",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
    ]
