# Generated by Django 4.2.15 on 2024-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "previous_years",
            "0005_alter_archivedactualuploadmonthlyfigure_financial_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplehistoryarchivedactualuploadmonthlyfigure",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical archived actual upload monthly figure",
                "verbose_name_plural": "historical archived actual upload monthly figures",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryarchivedfinancialcode",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical archived financial code",
                "verbose_name_plural": "historical archived financial codes",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryarchivedforecastdata",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical archived forecast data",
                "verbose_name_plural": "historical archived forecast datas",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryarchivedforecastdataupload",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical archived forecast data upload",
                "verbose_name_plural": "historical archived forecast data uploads",
            },
        ),
        migrations.AlterField(
            model_name="simplehistoryarchivedactualuploadmonthlyfigure",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryarchivedfinancialcode",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryarchivedforecastdata",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryarchivedforecastdataupload",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
