# Generated by Django 3.2.7 on 2022-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mi_report_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDataView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('financial_year_id', models.IntegerField()),
                ('budget', models.BigIntegerField(default=0)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_data_query',
                'managed': False,
            },
        ),
    ]
