# Generated by Django 3.2.13 on 2022-08-18 16:00

from django.db import migrations

drop_previous_year_sql = """
DROP VIEW IF EXISTS
	mi_report_previous_year_actual;


"""

create_previous_year_sql = """

CREATE VIEW
	mi_report_previous_year_actual as	
SELECT financial_year_id + 1 as financial_year_id, 
        financial_code_id,
        12 as archived_period_id,
            unnest(array[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]) as financial_period_id, 
            unnest(array[apr, may, jun, jul, aug, sep, 
                    oct, nov, "dec", jan, feb, mar, adj1, adj2, adj3]) as previous_year_actual
    FROM previous_years_archivedforecastdata
     WHERE
         (financial_year_id + 1) in 
         (SELECT financial_year FROM core_financialyear where current = true)
        ;

"""


class Migration(migrations.Migration):

    dependencies = [
        ('mi_report_data', '0002_model'),
    ]

    operations = [
        migrations.RunSQL(
            f"{drop_previous_year_sql} {create_previous_year_sql}",
            drop_previous_year_sql,
        ),
    ]
