# Generated by Django 3.2.13 on 2022-04-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_report_data', '0002_reportdataview'),
    ]

    operations = [
        migrations.RunSQL(
            """
                DROP materialized VIEW if exists  mi_report_periods;
         CREATE materialized VIEW mi_report_periods
                 AS
                 SELECT f.financial_period_code AS financial_period_id,
                    a.financial_period_code AS archived_period_id
                   FROM forecast_financialperiod f
                     CROSS JOIN forecast_financialperiod a;

        """,
            """
                DROP VIEW if exists mi_report_periods;
                """,
        ),
        migrations.RunSQL(
            """
            DROP VIEW if exists mi_report_empty_data;            
            CREATE VIEW mi_report_empty_data as
                  SELECT financial_code_id,
                    0 AS budget,
                    0 AS forecast,
                    0 AS actual,
                    financial_period_id,
                    financial_year_id,
                    archived_period_id
                   FROM (
                    SELECT DISTINCT forecast_budgetmonthlyfigure.financial_code_id,
                    forecast_budgetmonthlyfigure.financial_year_id
                   FROM forecast_budgetmonthlyfigure
                        UNION
                 SELECT DISTINCT forecast_forecastmonthlyfigure.financial_code_id,
                    forecast_forecastmonthlyfigure.financial_year_id
                   FROM forecast_forecastmonthlyfigure
                ) a
                     CROSS JOIN mi_report_periods;

        """,
            """
                DROP VIEW if exists mi_report_empty_data;
                """,
        ),
        migrations.RunSQL(
            """
            DROP  VIEW if exists mi_report_full_data;
            CREATE  view mi_report_full_data as 
                SELECT financial_code_id, 
                sum(budget) as budget, 
                sum(forecast) as forecast, 
                sum(actual) as actual, 
                    financial_period_id, financial_year_id, archived_period_id
                from
                (
                SELECT financial_code_id, budget, forecast, actual, financial_period_id, financial_year_id, archived_period_id
                    FROM public.mi_report_empty_data
                union all 
                SELECT financial_code_id, budget, forecast, actual, financial_period_id, financial_year_id, archived_period_id
                    FROM public.mi_report_data_query
                ) d

                group by financial_code_id, financial_period_id, financial_year_id, archived_period_id;                   
        """,
            """
                DROP  VIEW if exists mi_report_full_data;
                """,
        ),

    ]
