# Generated by Django 3.2.15 on 2022-09-12 11:10

from django.db import migrations, models

drop_sql = """
DROP VIEW IF EXISTS mi_report_future_year_forecast;
DROP VIEW IF EXISTS mi_report_future_year_budget;
"""

create_sql = """
CREATE VIEW mi_report_future_year_forecast AS
    SELECT financial_code_id, financial_year_id, financial_period_id, amount as future_forecast, 
        COALESCE(archived_status_id, ar.archived_period_id) as archived_period_id
        FROM public.forecast_forecastmonthlyfigure, (SELECT min(archived_period_id) as archived_period_id
        FROM end_of_month_endofmonthstatus where archived = false) ar        
        WHERE financial_year_id > (SELECT financial_year FROM core_financialyear where current = true)
        AND financial_period_id < 13;


CREATE VIEW mi_report_future_year_budget AS
    SELECT financial_code_id, financial_year_id, financial_period_id, amount as future_budget, 
        COALESCE(archived_status_id, ar.archived_period_id) as archived_period_id
        FROM public.forecast_budgetmonthlyfigure, (SELECT min(archived_period_id) as archived_period_id
        FROM end_of_month_endofmonthstatus where archived = false) ar        
        WHERE financial_year_id > (SELECT financial_year FROM core_financialyear where current = true)
        AND financial_period_id < 13;

"""


class Migration(migrations.Migration):

    dependencies = [
        ('mi_report_data', '0003_previous_year'),
    ]

    operations = [
        migrations.RunSQL(
            f"{drop_sql} {create_sql}",
            drop_sql,
        ),
        migrations.CreateModel(
            name='ReportFutureForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('financial_year_id', models.IntegerField()),
                ('future_forecast', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_future_year_forecast',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportFutureBudgetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('financial_year_id', models.IntegerField()),
                ('future_budget', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_future_year_budget',
                'managed': False,
            },
        ),
    ]
