# Generated by Django 3.2.13 on 2022-04-26 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mi_report_data", "0003_auto_20220426_0741"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="reportdataview",
            table="mi_report_full_data",
        ),
    ]
