# Generated by Django 3.2.15 on 2022-10-06 16:27

from django.db import migrations

drop_sql = """
DROP VIEW IF EXISTS
	mi_report_forecast_period_0_view;

DROP VIEW IF EXISTS
	mi_report_budget_period_0_view;
	
"""

# There is no period 0 in FFT, but it exists in the reports
# Use the first archived budget as period 0 data both for forecast and budget
create_sql = """
CREATE VIEW mi_report_forecast_period_0_view as
    SELECT 0 as archived_period_id, financial_code_id, financial_year_id, financial_period_id, 0 as actual, budget as forecast
        FROM public.mi_report_archived_budget_view where archived_period_id = 1;
        
CREATE VIEW mi_report_budget_period_0_view as
    SELECT 0 as archived_period_id, financial_code_id, financial_year_id, financial_period_id, budget 
        FROM public.mi_report_archived_budget_view where archived_period_id = 1;
        
"""
class Migration(migrations.Migration):

    dependencies = [
        ('mi_report_data', '0004_reportfutureyeardata'),
    ]

    operations = [
        migrations.RunSQL(
            f"{drop_sql} {create_sql}",
            drop_sql,
        ),
    ]
