# Generated by Django 3.2.15 on 2022-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_report_data", "0005_period_0_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportBudgetPeriod0Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year_id", models.IntegerField()),
                ("budget", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "mi_report_budget_period_0_view",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReportPeriod0DataView",
            fields=[
                ("financial_year_id", models.IntegerField()),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("forecast", models.BigIntegerField(default=0)),
                ("actual", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "mi_report_forecast_period_0_view",
                "managed": False,
            },
        ),
    ]
