# Generated by Django 3.2.15 on 2022-10-07 09:21

from django.db import migrations

drop_sql = """
DROP VIEW IF EXISTS
	mi_report_future_year_period_0_budget;
DROP VIEW IF EXISTS
	mi_report_future_year_period_0_forecast;

"""

create_sql = """
CREATE VIEW mi_report_future_year_period_0_budget as
    SELECT financial_code_id, financial_year_id, financial_period_id, future_budget, 0 as archived_period_id
        FROM public.mi_report_future_year_budget WHERE archived_period_id = 1;


CREATE VIEW mi_report_future_year_period_0_forecast as
    SELECT financial_code_id, financial_year_id, financial_period_id, future_budget as future_forecast, 0 as archived_period_id
        FROM public.mi_report_future_year_budget WHERE archived_period_id = 1;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("mi_report_data", "0006_period_0_model"),
    ]

    operations = [
        migrations.RunSQL(
            f"{drop_sql} {create_sql}",
            drop_sql,
        ),
    ]
