# Generated by Django 3.2.13 on 2022-08-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_report_data', '0006_reportmonthlydataview_reportpreviousmonthdataview_reportpreviousyeardata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAdj1DataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_adj1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportAdj2DataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_adj2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportAdj3DataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_adj3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportAprDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_apr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportAugDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_aug',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportDecDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_dec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportFebDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_feb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportJanDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_jan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportJulDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_jul',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportJunDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_jun',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportMarDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_mar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportMayDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_may',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportNovDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_nov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportOctDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_oct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportSepDataView',
            fields=[
                ('financial_year_id', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('forecast', models.BigIntegerField(default=0)),
                ('actual', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_monthly_forecast_sep',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ReportMonthlyDataView',
        ),
    ]
