# Generated by Django 3.2.13 on 2022-08-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_report_data', '0009_create_previous_years_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportpreviousyeardataview',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='reportpreviousyeardataview',
            table='mi_report_previous_year_actual',
        ),
        migrations.DeleteModel(
            name='ReportPreviousYearData',
        ),
    ]
