# Generated by Django 3.2.13 on 2022-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_report_data', '0010_auto_20220816_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCurrentActualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_id', models.IntegerField()),
                ('amount', models.BigIntegerField(default=0)),
                ('forecast', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_current_actual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportCurrentForecastData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_id', models.IntegerField()),
                ('amount', models.BigIntegerField(default=0)),
                ('forecast', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'mi_report_current_forecast',
                'managed': False,
            },
        ),
    ]
