# Generated by Django 3.2.13 on 2022-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mi_report_data", "0013_auto_20220818_1315"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportBudgetCurrentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("financial_year_id", models.IntegerField()),
                ("budget", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "mi_report_current_budget_view",
                "managed": False,
            },
        ),
    ]
