# Generated by Django 5.1 on 2024-09-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('directorate', models.CharField(max_length=255)),
                ('cc', models.CharField(max_length=255)),
                ('cc_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('se_no', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(max_length=10)),
                ('employee_location_city_name', models.CharField(max_length=255)),
                ('person_type', models.CharField(max_length=255)),
                ('assignment_status', models.CharField(max_length=255)),
                ('appointment_status', models.CharField(max_length=255)),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fte', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wmi_person', models.CharField(blank=True, max_length=255, null=True)),
                ('wmi', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_group', models.CharField(max_length=255)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superannuation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ernic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costing_cc', models.CharField(max_length=255)),
                ('return_field', models.CharField(max_length=255)),
                ('programme_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'HR',
                'verbose_name_plural': 'HR Records',
            },
        ),
    ]
