# Generated by Django 4.2.11 on 2024-03-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20220427_1046"),
        ("treasuryCOA", "0002_auto_20200820_0751"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicl5account",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
    ]
