# Generated by Django 4.2.15 on 2024-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasuryCOA", "0003_alter_historicl5account_financial_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplehistoryhistoricl5account",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Archived Treasury Level 5 COA",
                "verbose_name_plural": "historical Archived Treasury Level 5 COAs",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryl1account",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Treasury Level 1 COA",
                "verbose_name_plural": "historical Treasury Level 1 COAs",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryl2account",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Treasury Level 2 COA",
                "verbose_name_plural": "historical Treasury Level 2 COAs",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryl3account",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Treasury Level 3 COA",
                "verbose_name_plural": "historical Treasury Level 3 COAs",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryl4account",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Treasury Level 4 COA",
                "verbose_name_plural": "historical Treasury Level 4 COAs",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryl5account",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Treasury Level 5 COA",
                "verbose_name_plural": "historical Treasury Level 5 COAs",
            },
        ),
        migrations.AlterField(
            model_name="simplehistoryhistoricl5account",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryl1account",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryl2account",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryl3account",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryl4account",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryl5account",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
