# Generated by Django 5.1 on 2024-08-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('cost_centre', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('line_description', models.TextField()),
                ('net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiscal_period', models.CharField(max_length=100)),
                ('date_of_journal', models.DateField()),
                ('purchase_order_number', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=100)),
                ('level4_code', models.CharField(max_length=100)),
            ],
        ),
    ]
