# Generated by Django 3.2.4 on 2021-06-29 14:06

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.core.management import call_command
from django.db import migrations, models


def set_outturn(apps, schemaeditor):
    call_command(
        "calculate_all_outturns",
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forecast", "0006_auto_20210312_1632"),
        ("end_of_month", "0009_create_views_20200620_0842"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleHistoryMonthlyOutturn",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("updated", models.DateTimeField(blank=True, editable=False)),
                ("previous_outturn", models.BigIntegerField(default=0)),
                ("used_for_current_month", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField()),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "next_forecast_period",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="forecast.financialperiod",
                    ),
                ),
                (
                    "financial_code",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="forecast.financialcode",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.financialyear",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "outturn_period",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="forecast.financialperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Archived outturn",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": "history_date",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MonthlyOutturn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("previous_outturn", models.BigIntegerField(default=0)),
                ("used_for_current_month", models.BooleanField(default=False)),
                (
                    "next_forecast_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="end_of_month_monthlyoutturns",
                        to="forecast.financialperiod",
                    ),
                ),
                (
                    "financial_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="end_of_month_monthlyoutturns",
                        to="forecast.financialcode",
                    ),
                ),
                (
                    "financial_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.financialyear",
                    ),
                ),
                (
                    "outturn_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="end_of_month_outturn_period",
                        to="forecast.financialperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archived outturn",
                "verbose_name_plural": "Archived outturns",
                "ordering": ["outturn_period"],
                "unique_together": {("financial_code", "outturn_period")},
            },
        ),
        migrations.RunPython(set_outturn),
    ]
