# Generated by Django 3.2.7 on 2022-01-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0008_amend_views_20210802_1439"),
        ("core", "0011_alter_historicaluser_first_name"),
        ("end_of_month", "0011_amend_view_20210629_1406"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="monthlytotalbudget",
            unique_together={("financial_code", "archived_status", "financial_year")},
        ),
    ]
