# Generated by Django 4.2.11 on 2024-03-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0010_amend_forecast_forecast_budget_view"),
        ("end_of_month", "0012_alter_monthlytotalbudget_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endofmonthstatus",
            name="archived_period",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyoutturn",
            name="financial_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="forecast.financialcode",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyoutturn",
            name="next_forecast_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyoutturn",
            name="outturn_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="monthlytotalbudget",
            name="archived_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="monthlytotalbudget",
            name="archived_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="end_of_month.endofmonthstatus",
            ),
        ),
        migrations.AlterField(
            model_name="monthlytotalbudget",
            name="financial_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="forecast.financialcode",
            ),
        ),
    ]
