# Generated by Django 4.2.15 on 2024-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("end_of_month", "0013_alter_endofmonthstatus_archived_period_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplehistoryendofmonthstatus",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical End of Month Archive Status",
                "verbose_name_plural": "historical End of Month Archive Statuses",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorymonthlyoutturn",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Archived outturn",
                "verbose_name_plural": "historical Archived outturns",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorymonthlytotalbudget",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Archived total budget",
                "verbose_name_plural": "historical Archived total budget",
            },
        ),
        migrations.AlterField(
            model_name="simplehistoryendofmonthstatus",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorymonthlyoutturn",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorymonthlytotalbudget",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
