# Generated by Django 5.1 on 2024-08-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('group', models.CharField(max_length=100)),
                ('directorate', models.CharField(max_length=100)),
                ('cost_centre', models.CharField(max_length=100)),
                ('cost_centre_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('se_no', models.CharField(max_length=100, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(max_length=100)),
                ('employee_location_city_name', models.CharField(max_length=100)),
                ('person_type', models.CharField(max_length=100)),
                ('assignment_status', models.CharField(max_length=100)),
                ('appointment_status', models.CharField(max_length=100)),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fte', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wmi_person', models.CharField(max_length=100)),
                ('wmi', models.CharField(max_length=100)),
                ('actual_group', models.CharField(max_length=100)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superannuation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ernic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costing_cc', models.CharField(max_length=100)),
                ('return_field', models.CharField(max_length=100)),
            ],
        ),
    ]
