# Generated by Django 5.1 on 2024-09-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fte', models.FloatField()),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
