# Generated by Django 3.2.4 on 2021-06-24 10:27
from django.apps import apps
from django.contrib.auth.management import create_permissions
from django.db import migrations

Permission = apps.get_model('auth', 'Permission')
Group = apps.get_model('auth', 'Group')


def add_all_permissions():
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None


def assign_permissions(group, permission_codenames):
    for permission_codename in permission_codenames:
        permission = Permission.objects.get(
            codename=permission_codename,
        )
        group.permissions.add(
            permission,
        )


def add_split_project_admin_permissions(apps, schema_editor):
    add_all_permissions()

    split_project_adminstrators, _ = Group.objects.get_or_create(
        name='Project Split Administrator',
    )

    assign_permissions(
        split_project_adminstrators, [
            "can_upload_percentage_files"
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('split_project', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_split_project_admin_permissions),
    ]
