# Generated by Django 4.2.11 on 2024-03-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20220427_1046"),
        ("treasurySS", "0005_auto_20230428_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedsubsegment",
            name="control_budget_detail_code",
            field=models.CharField(
                choices=[
                    (
                        "AME",
                        (("DEPT AME", "DEPT AME"), ("NON-DEPT AME", "NON-DEPT AME")),
                    ),
                    ("DEL", (("DEL ADMIN", "DEL ADMIN"), ("DEL PROG", "DEL PROG"))),
                    ("NON-BUDGET", "NON-BUDGET"),
                ],
                default="NON-BUDGET",
                max_length=50,
                verbose_name="control budget detail code",
            ),
        ),
        migrations.AlterField(
            model_name="archivedsubsegment",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="simplehistoryarchivedsubsegment",
            name="control_budget_detail_code",
            field=models.CharField(
                choices=[
                    (
                        "AME",
                        (("DEPT AME", "DEPT AME"), ("NON-DEPT AME", "NON-DEPT AME")),
                    ),
                    ("DEL", (("DEL ADMIN", "DEL ADMIN"), ("DEL PROG", "DEL PROG"))),
                    ("NON-BUDGET", "NON-BUDGET"),
                ],
                default="NON-BUDGET",
                max_length=50,
                verbose_name="control budget detail code",
            ),
        ),
        migrations.AlterField(
            model_name="simplehistorysubsegment",
            name="control_budget_detail_code",
            field=models.CharField(
                choices=[
                    (
                        "AME",
                        (("DEPT AME", "DEPT AME"), ("NON-DEPT AME", "NON-DEPT AME")),
                    ),
                    ("DEL", (("DEL ADMIN", "DEL ADMIN"), ("DEL PROG", "DEL PROG"))),
                    ("NON-BUDGET", "NON-BUDGET"),
                ],
                default="NON-BUDGET",
                max_length=50,
                verbose_name="control budget detail code",
            ),
        ),
        migrations.AlterField(
            model_name="subsegment",
            name="control_budget_detail_code",
            field=models.CharField(
                choices=[
                    (
                        "AME",
                        (("DEPT AME", "DEPT AME"), ("NON-DEPT AME", "NON-DEPT AME")),
                    ),
                    ("DEL", (("DEL ADMIN", "DEL ADMIN"), ("DEL PROG", "DEL PROG"))),
                    ("NON-BUDGET", "NON-BUDGET"),
                ],
                default="NON-BUDGET",
                max_length=50,
                verbose_name="control budget detail code",
            ),
        ),
    ]
