# Generated by Django 5.1 on 2024-08-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('business_unit_number', models.CharField(max_length=100)),
                ('business_unit_name', models.CharField(max_length=100)),
                ('cost_center_number', models.CharField(max_length=100)),
                ('cost_center_name', models.CharField(max_length=100)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=100)),
                ('assignment_number', models.CharField(max_length=100)),
                ('payroll_name', models.CharField(max_length=100)),
                ('employee_organization', models.CharField(max_length=100)),
                ('employee_location', models.CharField(max_length=100)),
                ('person_type', models.CharField(max_length=100)),
                ('employee_category', models.CharField(max_length=100)),
                ('assignment_type', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('account_code', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('pay_element_name', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('debit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
