# Generated by Django 4.2.15 on 2024-10-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("costcentre", "0008_alter_simplehistoryarchivedcostcentre_options_and_more"),
        ("chartofaccountDIT", "0015_alter_simplehistoryanalysis1_options_and_more"),
        ("core", "0013_alter_historicalgroup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_no", models.CharField(max_length=8, unique=True)),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                (
                    "cost_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="costcentre.costcentre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayElementTypeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "natural_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.naturalcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayElementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.payelementtypegroup",
                    ),
                ),
                (
                    "natural_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.naturalcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeePayPeriods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_1", models.BooleanField(default=True)),
                ("period_2", models.BooleanField(default=True)),
                ("period_3", models.BooleanField(default=True)),
                ("period_4", models.BooleanField(default=True)),
                ("period_5", models.BooleanField(default=True)),
                ("period_6", models.BooleanField(default=True)),
                ("period_7", models.BooleanField(default=True)),
                ("period_8", models.BooleanField(default=True)),
                ("period_9", models.BooleanField(default=True)),
                ("period_10", models.BooleanField(default=True)),
                ("period_11", models.BooleanField(default=True)),
                ("period_12", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_periods",
                        to="payroll.employee",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.financialyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeePayElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("debit_amount", models.DecimalField(decimal_places=2, max_digits=9)),
                ("credit_amount", models.DecimalField(decimal_places=2, max_digits=9)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_element",
                        to="payroll.employee",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payroll.payelementtype",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="employeepayperiods",
            constraint=models.UniqueConstraint(
                fields=("employee", "year"), name="unique_employee_pay_periods"
            ),
        ),
    ]
