# Generated by Django 5.1 on 2024-09-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayroll',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('staff_number', models.CharField(max_length=100)),
                ('fte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('programme_code', models.CharField(max_length=100)),
                ('budget_type', models.CharField(max_length=100)),
                ('eu_non_eu', models.CharField(max_length=100)),
                ('assignment_status', models.CharField(max_length=100)),
                ('current_month', models.CharField(max_length=100)),
                ('current_year', models.CharField(max_length=100)),
                ('apr', models.IntegerField(verbose_name='april')),
                ('may', models.IntegerField(verbose_name='may')),
                ('jun', models.IntegerField(verbose_name='june')),
                ('jul', models.IntegerField(verbose_name='july')),
                ('aug', models.IntegerField(verbose_name='august')),
                ('sep', models.IntegerField(verbose_name='september')),
                ('oct', models.IntegerField(verbose_name='october')),
                ('nov', models.IntegerField(verbose_name='november')),
                ('dec', models.IntegerField(verbose_name='december')),
                ('jan', models.IntegerField(verbose_name='january')),
                ('feb', models.IntegerField(verbose_name='february')),
                ('mar', models.IntegerField(verbose_name='march')),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superannuation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ernic', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForcastPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nac', models.CharField(max_length=100)),
                ('nac_description', models.CharField(max_length=100)),
                ('project_code', models.CharField(max_length=100)),
                ('programme_code', models.CharField(max_length=100)),
                ('budget_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=255)),
                ('directorate', models.CharField(max_length=255)),
                ('cc', models.CharField(max_length=255)),
                ('cc_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('se_no', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(max_length=10)),
                ('employee_location_city_name', models.CharField(max_length=255)),
                ('person_type', models.CharField(max_length=255)),
                ('assignment_status', models.CharField(max_length=255)),
                ('appointment_status', models.CharField(max_length=255)),
                ('working_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fte', models.DecimalField(decimal_places=2, max_digits=4)),
                ('wmi_person', models.CharField(blank=True, max_length=255, null=True)),
                ('wmi', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_group', models.CharField(max_length=255)),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superannuation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ernic', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costing_cc', models.CharField(max_length=255)),
                ('return_field', models.CharField(max_length=255)),
                ('programme_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'HR',
                'verbose_name_plural': 'HR Records',
            },
        ),
        migrations.CreateModel(
            name='NonEmployeePayroll',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('staff_number', models.CharField(max_length=100)),
                ('fte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('programme_code', models.CharField(max_length=100)),
                ('budget_type', models.CharField(max_length=100)),
                ('eu_non_eu', models.CharField(max_length=100)),
                ('assignment_status', models.CharField(max_length=100)),
                ('person_type', models.CharField(max_length=100)),
                ('current_month', models.CharField(max_length=100)),
                ('current_year', models.CharField(max_length=100)),
                ('apr', models.IntegerField(verbose_name='april')),
                ('may', models.IntegerField(verbose_name='may')),
                ('jun', models.IntegerField(verbose_name='june')),
                ('jul', models.IntegerField(verbose_name='july')),
                ('aug', models.IntegerField(verbose_name='august')),
                ('sep', models.IntegerField(verbose_name='september')),
                ('oct', models.IntegerField(verbose_name='october')),
                ('nov', models.IntegerField(verbose_name='november')),
                ('dec', models.IntegerField(verbose_name='december')),
                ('jan', models.IntegerField(verbose_name='january')),
                ('feb', models.IntegerField(verbose_name='february')),
                ('mar', models.IntegerField(verbose_name='march')),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superannuation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ernic', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
