# Generated by Django 4.2.15 on 2024-10-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employeepayperiods",
            options={"verbose_name_plural": "employee pay periods"},
        ),
    ]
