# Generated by Django 4.2.15 on 2024-10-30 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartofaccountDIT", "0015_alter_simplehistoryanalysis1_options_and_more"),
        ("payroll", "0002_alter_employeepayperiods_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="programme_code",
            field=models.ForeignKey(
                default=338887,
                on_delete=django.db.models.deletion.PROTECT,
                to="chartofaccountDIT.programmecode",
            ),
            preserve_default=False,
        ),
    ]
