# Generated by Django 4.2.16 on 2024-11-11 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "gifthospitality",
            "0006_alter_simplehistorygiftandhospitality_options_and_more",
        ),
        ("chartofaccountDIT", "0015_alter_simplehistoryanalysis1_options_and_more"),
        ("payroll", "0003_employee_programme_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programme_switch_vacancy",
                    models.CharField(
                        choices=[("PS", "Programme Switch"), ("V", "Vacancy")],
                        max_length=2,
                        verbose_name="Programme switch / Vacancy",
                    ),
                ),
                (
                    "appointee_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hiring_manager",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("hr_ref", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gifthospitality.grade",
                    ),
                ),
                (
                    "programme_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chartofaccountDIT.programmecode",
                    ),
                ),
            ],
        ),
    ]
