# Generated by Django 4.2.16 on 2024-11-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0004_vacancy"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={"verbose_name_plural": "Vacancies"},
        ),
    ]
