# Generated by Django 4.2.16 on 2024-11-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_alter_vacancy_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="programme_switch_vacancy",
            field=models.CharField(
                choices=[
                    ("programme_switch", "Programme Switch"),
                    ("vacancy", "Vacancy"),
                ],
                max_length=16,
                verbose_name="Programme switch / Vacancy",
            ),
        ),
    ]
