# Generated by Django 4.2.16 on 2024-11-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0007_vacancy_cost_centre"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="recruitment_stage",
            field=models.IntegerField(
                choices=[
                    (1, "Preparing"),
                    (2, "Advert (Vac ref to be provided)"),
                    (3, "Sift"),
                    (4, "Interview"),
                    (5, "Onboarding"),
                    (6, "Unsuccessful recruitment"),
                    (7, "Not (yet) advertised"),
                    (8, "Not required"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="recruitment_type",
            field=models.CharField(
                choices=[
                    ("expression_of_interest", "Expression of Interest"),
                    (
                        "external_recruitment_non_bulk",
                        "External Recruitment (Non Bulk)",
                    ),
                    (
                        "external_recruitment_bulk",
                        "External Recruitment (Bulk campaign)",
                    ),
                    ("internal_managed_move", "Internal Managed Move"),
                    ("internal_redeployment", "Internal Redeployment"),
                    ("other", "Other"),
                    ("inactive_post", "Inactive Post"),
                    ("expected_unknown_leavers", "Expected Unknown Leavers"),
                    ("missing_staff", "Missing Staff"),
                ],
                default="expression_of_interest",
                max_length=29,
            ),
        ),
    ]
