# Generated by Django 4.2.16 on 2024-11-13 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0008_vacancy_recruitment_stage_vacancy_recruitment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="programme_switch_vacancy",
        ),
    ]
