# Generated by Django 4.2.16 on 2024-11-18 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0010_alter_vacancy_appointee_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="appointee_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, spaces, - and ' are allowed.",
                        regex="^[a-zA-Z '-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="hiring_manager",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, spaces, - and ' are allowed.",
                        regex="^[a-zA-Z '-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="hr_ref",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, spaces, - and ' are allowed.",
                        regex="^[a-zA-Z '-]*$",
                    )
                ],
            ),
        ),
    ]
