# Generated by Django 4.2.16 on 2024-11-12 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gifthospitality",
            "0006_alter_simplehistorygiftandhospitality_options_and_more",
        ),
        ("payroll", "0011_alter_vacancy_appointee_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="assignment_status",
            field=models.CharField(default="Active Assignment", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="fte",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="employee",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gifthospitality.grade",
            ),
        ),
    ]
