# Generated by Django 4.2.16 on 2024-11-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gifthospitality",
            "0006_alter_simplehistorygiftandhospitality_options_and_more",
        ),
        ("core", "0013_alter_historicalgroup_options_and_more"),
        ("payroll", "0012_employee_assignment_status_employee_fte_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="fte",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gifthospitality.grade",
            ),
        ),
        migrations.CreateModel(
            name="VacancyPayPeriods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_1", models.BooleanField(default=True)),
                ("period_2", models.BooleanField(default=True)),
                ("period_3", models.BooleanField(default=True)),
                ("period_4", models.BooleanField(default=True)),
                ("period_5", models.BooleanField(default=True)),
                ("period_6", models.BooleanField(default=True)),
                ("period_7", models.BooleanField(default=True)),
                ("period_8", models.BooleanField(default=True)),
                ("period_9", models.BooleanField(default=True)),
                ("period_10", models.BooleanField(default=True)),
                ("period_11", models.BooleanField(default=True)),
                ("period_12", models.BooleanField(default=True)),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pay_periods",
                        to="payroll.vacancy",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.financialyear",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "vacancy pay periods",
            },
        ),
        migrations.AddConstraint(
            model_name="vacancypayperiods",
            constraint=models.UniqueConstraint(
                fields=("vacancy", "year"), name="unique_vacancy_pay_periods"
            ),
        ),
    ]
