# Generated by Django 4.2.16 on 2024-11-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0013_vacancy_fte_alter_vacancy_grade_vacancypayperiods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="basic_pay",
            field=models.BigIntegerField(db_comment="pence", default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="ernic",
            field=models.BigIntegerField(db_comment="pence", default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="pension",
            field=models.BigIntegerField(db_comment="pence", default=0),
        ),
    ]
