# Generated by Django 5.1.4 on 2025-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0015_employee_basic_pay_employee_ernic_employee_pension"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="has_left",
            field=models.BooleanField(default=False),
        ),
    ]
