# Generated by Django 5.1.5 on 2025-01-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0016_employee_has_left"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payelementtype",
            name="group",
        ),
        migrations.RemoveField(
            model_name="payelementtype",
            name="natural_code",
        ),
        migrations.DeleteModel(
            name="EmployeePayElement",
        ),
        migrations.DeleteModel(
            name="PayElementType",
        ),
    ]
