# Generated by Django 5.1.5 on 2025-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0017_remove_payelementtype_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeepayperiods",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="vacancypayperiods",
            name="notes",
            field=models.TextField(default=""),
        ),
    ]
