# Generated by Django 5.1.5 on 2025-03-17 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0018_employeepayperiods_notes_vacancypayperiods_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="hr_ref",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, numbers, spaces, - and ' are allowed.",
                        regex="^[a-zA-Z0-9 '-]*$",
                    )
                ],
            ),
        ),
    ]
