# Generated by Django 5.1.5 on 2025-03-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifthospitality", "0007_alter_grade_grade_alter_simplehistorygrade_grade"),
        ("payroll", "0019_alter_vacancy_hr_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="grade",
            field=models.ForeignKey(
                default="Not set",
                on_delete=django.db.models.deletion.PROTECT,
                to="gifthospitality.grade",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="grade",
            field=models.ForeignKey(
                default="Not set",
                on_delete=django.db.models.deletion.PROTECT,
                to="gifthospitality.grade",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="recruitment_stage",
            field=models.IntegerField(
                choices=[
                    (1, "Preparing"),
                    (2, "Advert - Vacancy reference to be provided"),
                    (3, "Sift"),
                    (4, "Interview"),
                    (5, "Onboarding"),
                    (6, "Unsuccessful recruitment"),
                    (7, "Not yet advertised"),
                    (8, "Not required"),
                ],
                default=1,
            ),
        ),
    ]
