# Generated by Django 5.1.5 on 2025-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0021_alter_employee_grade_alter_vacancy_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="recruitment_stage",
            field=models.IntegerField(
                choices=[
                    (1, "Preparing"),
                    (2, "Advert - vacancy reference to be provided"),
                    (3, "Sift"),
                    (4, "Interview"),
                    (5, "Onboarding"),
                    (6, "Unsuccessful recruitment"),
                    (7, "Not yet advertised"),
                    (8, "Not required"),
                ],
                default=1,
            ),
        ),
    ]
