# Generated by Django 5.1.5 on 2025-03-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0022_alter_vacancy_recruitment_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_payroll",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(basic_pay__gt=0, then=True), default=False
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
