# Generated by Django 5.1.7 on 2025-04-03 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0023_employee_is_payroll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="appointee_name",
            field=models.CharField(
                blank=True,
                help_text="Only if you have their name",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, spaces, - and ' are allowed.",
                        regex="^[a-zA-Z '-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="hr_ref",
            field=models.CharField(
                blank=True,
                help_text="A six digit number given by HR",
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only letters, numbers, spaces, - and ' are allowed.",
                        regex="^[a-zA-Z0-9 '-]*$",
                    )
                ],
                verbose_name="HR reference",
            ),
        ),
    ]
