# Generated by Django 5.1.7 on 2025-05-20 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0024_alter_vacancy_appointee_name_alter_vacancy_hr_ref"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
