# Generated by Django 3.2.16 on 2023-04-03 10:35

from django.db import migrations, models

def update_pay(apps, schema_editor):
    NacCategory = apps.get_model("chartofaccountDIT", "naccategory")

    model_obj, _ = NacCategory.objects.filter(NAC_category_description="Pay")
    model_obj.pay_nonpay = NacCategory.PAY
    model_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0011_auto_20210430_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedexpenditurecategory',
            name='NAC_pay_nonpay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pay Non-Pay'),
        ),
        migrations.AddField(
            model_name='naccategory',
            name='pay_nonpay',
            field=models.CharField(choices=[('P', 'Pay'), ('NP', 'Non Pay')], default='NP', max_length=20),
        ),
        migrations.AddField(
            model_name='naturalcode',
            name='cash_non_cash',
            field=models.CharField(choices=[('CH', 'Cash'), ('NC', 'Non-Cash'), ('NA', 'N/A Cash')], default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='naturalcode',
            name='gross_income',
            field=models.CharField(blank=True, choices=[('GR', 'Gross'), ('IN', 'Income')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='simplehistoryarchivedexpenditurecategory',
            name='NAC_pay_nonpay',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pay Non-Pay'),
        ),
        migrations.AddField(
            model_name='simplehistorynaccategory',
            name='pay_nonpay',
            field=models.CharField(choices=[('P', 'Pay'), ('NP', 'Non Pay')], default='NP', max_length=20),
        ),
        migrations.AddField(
            model_name='simplehistorynaturalcode',
            name='cash_non_cash',
            field=models.CharField(choices=[('CH', 'Cash'), ('NC', 'Non-Cash'), ('NA', 'N/A Cash')], default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='simplehistorynaturalcode',
            name='gross_income',
            field=models.CharField(blank=True, choices=[('GR', 'Gross'), ('IN', 'Income')], max_length=20, null=True),
        ),
        migrations.RunPython(update_pay),
    ]
