# Generated by Django 3.2.7 on 2022-01-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0011_auto_20210430_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcomapping',
            name='account_L6_code_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chartofaccountDIT.naturalcode'),
        ),
    ]
