# Generated by Django 3.2.16 on 2023-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chartofaccountDIT', '0012_auto_20230406_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedfcomapping',
            name='account_L6_code',
            field=models.IntegerField(verbose_name='Oracle (DBT) Code'),
        ),
        migrations.AlterField(
            model_name='archivedfcomapping',
            name='account_L6_description',
            field=models.CharField(max_length=200, verbose_name='Oracle (DBT) Description'),
        ),
        migrations.AlterField(
            model_name='simplehistoryarchivedfcomapping',
            name='account_L6_code',
            field=models.IntegerField(verbose_name='Oracle (DBT) Code'),
        ),
        migrations.AlterField(
            model_name='simplehistoryarchivedfcomapping',
            name='account_L6_description',
            field=models.CharField(max_length=200, verbose_name='Oracle (DBT) Description'),
        ),
    ]
