# Generated by Django 4.2.11 on 2024-03-18 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_auto_20220427_1046"),
        ("chartofaccountDIT", "0013_auto_20230428_1106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivedanalysis1",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="archivedanalysis2",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="archivedcommercialcategory",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="archivedexpenditurecategory",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="archivedfcomapping",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="archivedinterentity",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="archivednaturalcode",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="archivedprogrammecode",
            name="budget_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="chartofaccountDIT.budgettype",
                verbose_name="Budget Type",
            ),
        ),
        migrations.AlterField(
            model_name="archivedprogrammecode",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="archivedprojectcode",
            name="financial_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="core.financialyear",
            ),
        ),
        migrations.AlterField(
            model_name="programmecode",
            name="budget_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s",
                to="chartofaccountDIT.budgettype",
                verbose_name="Budget Type",
            ),
        ),
    ]
