# Generated by Django 3.0.3 on 2021-03-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0005_data_period_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialperiod',
            name='actual_loaded_previous_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simplehistoryfinancialperiod',
            name='actual_loaded_previous_year',
            field=models.BooleanField(default=False),
        ),
    ]
