# Generated by Django 3.2.4 on 2021-07-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0006_auto_20210312_1632"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OSCARReturn",
        ),
        migrations.RunSQL(
            'DROP VIEW if exists "forecast_oscarreturn";',
        ),
    ]
