# Generated by Django 3.0.3 on 2021-03-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0006_auto_20210312_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastmonthlyfigure',
            name='oracle_amount',
            field=models.BigIntegerField(default=0, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='simplehistoryforecastmonthlyfigure',
            name='oracle_amount',
            field=models.BigIntegerField(default=0, null=True, blank=True),
        ),
    ]
