# Generated by Django 3.2.4 on 2021-06-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0007_delete_oscarreturn"),
        (
            "end_of_month",
            "0010_monthlypreviousoutturn_simplehistorymonthlypreviousoutturn",
        ),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW if exists forecast_forecast_budget_view CASCADE;
            CREATE VIEW public.forecast_forecast_budget_view
            as
            SELECT coalesce(b.financial_code_id, f.financial_code_id) as financial_code_id,
                    coalesce(b.financial_year_id, f.financial_year_id) as financial_year,
                    coalesce(budget, 0) as budget,
                    coalesce(apr, 0) as apr,
                    coalesce(may, 0) as may,
                    coalesce(jun, 0) as jun,
                    coalesce(jul, 0) as jul,
                    coalesce(aug, 0) as aug,
                    coalesce(sep, 0) as sep,
                    coalesce(oct, 0) as oct,
                    coalesce(nov, 0) as nov,
                    coalesce("dec", 0) as "dec",
                    coalesce(jan, 0) as jan,
                    coalesce(feb, 0) as feb,
                    coalesce(mar, 0) as mar,
                    coalesce(adj1, 0) as adj1,
                    coalesce(adj2, 0) as adj2,
                    coalesce(adj3, 0) as adj3,
                    coalesce(previous_outturn, 0) as previous_outturn
            FROM annual_forecast f 
                FULL OUTER JOIN yearly_budget b
                    on b.financial_code_id = f.financial_code_id and b.financial_year_id = f.financial_year_id                    
                FULL OUTER JOIN end_of_month_monthlyoutturn o
                    on o.financial_code_id = f.financial_code_id and o.financial_year_id = f.financial_year_id and o.used_for_current_month = True;                                
 
 
            DROP VIEW if exists forecast_forecast_download_view ;
            CREATE VIEW public.forecast_forecast_download_view
            as
            SELECT ROW_NUMBER () 
                OVER (ORDER BY coalesce(fc.id, f.financial_code_id)) as id,          
                    coalesce(fc.id, f.financial_code_id) as financial_code_id,
                    financial_year,
                    coalesce(budget, 0) as budget,
                    coalesce(apr, 0) as apr,
                    coalesce(may, 0) as may,
                    coalesce(jun, 0) as jun,
                    coalesce(jul, 0) as jul,
                    coalesce(aug, 0) as aug,
                    coalesce(sep, 0) as sep,
                    coalesce(oct, 0) as oct,
                    coalesce(nov, 0) as nov,
                    coalesce("dec", 0) as "dec",
                    coalesce(jan, 0) as jan,
                    coalesce(feb, 0) as feb,
                    coalesce(mar, 0) as mar,
                    coalesce(adj1, 0) as adj1,
                    coalesce(adj2, 0) as adj2,
                    coalesce(adj3, 0) as adj3,
                    coalesce(previous_outturn, 0) as previous_outturn
            FROM forecast_forecast_budget_view f 
                FULL OUTER JOIN forecast_financialcode fc
                    on fc.id = f.financial_code_id;                    
          """,
        ),
    ]
