# Generated by Django 4.2.11 on 2024-03-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("end_of_month", "0013_alter_endofmonthstatus_archived_period_and_more"),
        ("forecast", "0010_amend_forecast_forecast_budget_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actualuploadmonthlyfigure",
            name="financial_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialcode",
            ),
        ),
        migrations.AlterField(
            model_name="actualuploadmonthlyfigure",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="budgetmonthlyfigure",
            name="archived_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="end_of_month.endofmonthstatus",
            ),
        ),
        migrations.AlterField(
            model_name="budgetmonthlyfigure",
            name="financial_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialcode",
            ),
        ),
        migrations.AlterField(
            model_name="budgetmonthlyfigure",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="budgetuploadmonthlyfigure",
            name="financial_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialcode",
            ),
        ),
        migrations.AlterField(
            model_name="budgetuploadmonthlyfigure",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
        migrations.AlterField(
            model_name="forecastmonthlyfigure",
            name="financial_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialcode",
            ),
        ),
        migrations.AlterField(
            model_name="forecastmonthlyfigure",
            name="financial_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)ss",
                to="forecast.financialperiod",
            ),
        ),
    ]
