# Generated by Django 4.2.15 on 2024-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecast", "0011_alter_actualuploadmonthlyfigure_financial_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplehistoryactualuploadmonthlyfigure",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical actual upload monthly figure",
                "verbose_name_plural": "historical actual upload monthly figures",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorybudgetmonthlyfigure",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical budget monthly figure",
                "verbose_name_plural": "historical budget monthly figures",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorybudgetuploadmonthlyfigure",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical budget upload monthly figure",
                "verbose_name_plural": "historical budget upload monthly figures",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryfinancialcode",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical financial code",
                "verbose_name_plural": "historical financial codes",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryfinancialperiod",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical financial period",
                "verbose_name_plural": "historical financial periods",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryforecasteditstate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical forecast edit state",
                "verbose_name_plural": "historical Forecast edit state",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryforecastexpendituretype",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical forecast expenditure type",
                "verbose_name_plural": "historical forecast expenditure types",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryforecastmonthlyfigure",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical forecast monthly figure",
                "verbose_name_plural": "historical forecast monthly figures",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryfutureforecasteditstate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical future forecast edit state",
                "verbose_name_plural": "historical Future forecast edit state",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistoryunlockedforecasteditor",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical unlocked forecast editor",
                "verbose_name_plural": "historical unlocked forecast editors",
            },
        ),
        migrations.AlterField(
            model_name="simplehistoryactualuploadmonthlyfigure",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorybudgetmonthlyfigure",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorybudgetuploadmonthlyfigure",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryfinancialcode",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryfinancialperiod",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryforecasteditstate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryforecastexpendituretype",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryforecastmonthlyfigure",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryfutureforecasteditstate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistoryunlockedforecasteditor",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
