# Generated by Django 5.1 on 2024-09-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZeroTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('cost_centre', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=100)),
                ('analysis_1', models.CharField(max_length=100)),
                ('spare_1', models.CharField(blank=True, max_length=100, null=True)),
                ('spare_2', models.CharField(blank=True, max_length=100, null=True)),
                ('apr', models.FloatField()),
                ('may', models.FloatField()),
                ('jun', models.FloatField()),
                ('jul', models.FloatField()),
                ('aug', models.FloatField()),
                ('sep', models.FloatField()),
                ('oct', models.FloatField()),
                ('nov', models.FloatField()),
                ('dec', models.FloatField()),
                ('jan', models.FloatField()),
                ('feb', models.FloatField()),
                ('mar', models.FloatField()),
                ('adj1', models.FloatField(blank=True, null=True)),
                ('adj2', models.FloatField(blank=True, null=True)),
                ('adj3', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Zero Transaction Entries',
            },
        ),
    ]
