# Generated by Django 3.2.12 on 2022-04-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_download', 'Can download active users')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
