# Generated by Django 4.2.15 on 2024-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifthospitality", "0005_auto_20230428_1106"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplehistorygiftandhospitality",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Gift and Hospitality",
                "verbose_name_plural": "historical Gift and Hospitality",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorygiftandhospitalitycategory",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Gift and Hospitality Category",
                "verbose_name_plural": "historical Gift and Hospitality Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorygiftandhospitalityclassification",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Gift and Hospitality Type",
                "verbose_name_plural": "historical Gift and Hospitality Types",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorygiftandhospitalitycompany",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Gift and Hospitality Company",
                "verbose_name_plural": "historical Gift and Hospitality Companies",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorygrade",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Grade",
                "verbose_name_plural": "historical Grades",
            },
        ),
        migrations.AlterField(
            model_name="simplehistorygiftandhospitality",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorygiftandhospitalitycategory",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorygiftandhospitalityclassification",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorygiftandhospitalitycompany",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorygrade",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
