# Generated by Django 5.1.5 on 2025-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gifthospitality",
            "0006_alter_simplehistorygiftandhospitality_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="grade",
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="simplehistorygrade",
            name="grade",
            field=models.CharField(db_index=True, max_length=12),
        ),
    ]
