# Generated by Django 4.2.16 on 2024-11-14 15:11

import time

from django.db import migrations


def forward(apps, schema_editor):
    Grade = apps.get_model("gifthospitality", "Grade")


def reverse(apps, schema_editor):
    Grade = apps.get_model("gifthospitality", "Grade")


class Migration(migrations.Migration):

    dependencies = [
        (
            "gifthospitality",
            "0006_alter_simplehistorygiftandhospitality_options_and_more",
        ),
    ]

    operations = [migrations.RunPython(forward, reverse)]
