# Generated by Django 3.2.4 on 2021-08-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costcentre', '0004_auto_20200828_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedcostcentre',
            name='treasury_segment_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='segment code'),
        ),
        migrations.AddField(
            model_name='simplehistoryarchivedcostcentre',
            name='treasury_segment_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='segment code'),
        ),
    ]
