# Generated by Django 4.2.15 on 2024-10-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costcentre", "0007_alter_archivedcostcentre_financial_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simplehistoryarchivedcostcentre",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Archived Cost Centre",
                "verbose_name_plural": "historical Archived Cost Centres",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorybsceemail",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical BSCE Email",
                "verbose_name_plural": "historical BSCE Emails",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorybusinesspartner",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Business Partner",
                "verbose_name_plural": "historical Business Partners",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorycostcentre",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Cost Centre",
                "verbose_name_plural": "historical Cost Centres",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorycostcentreperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Hierarchy Responsibility",
                "verbose_name_plural": "historical Hierarchy Responsibilities",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorydepartmentalgroup",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Departmental Group",
                "verbose_name_plural": "historical Departmental Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="simplehistorydirectorate",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Directorate",
                "verbose_name_plural": "historical Directorates",
            },
        ),
        migrations.AlterField(
            model_name="simplehistoryarchivedcostcentre",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorybsceemail",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorybusinesspartner",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorycostcentre",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorycostcentreperson",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorydepartmentalgroup",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="simplehistorydirectorate",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
