# Generated by Django 5.1.7 on 2025-03-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costcentre", "0008_alter_simplehistoryarchivedcostcentre_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedcostcentre",
            name="is_overseas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="costcentre",
            name="is_overseas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="simplehistoryarchivedcostcentre",
            name="is_overseas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="simplehistorycostcentre",
            name="is_overseas",
            field=models.BooleanField(default=False),
        ),
    ]
