# Generated by Django 3.2.4 on 2021-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurySS', '0004_auto_20210818_1002'),
        ('oscar_return', '0001_initial'),
        ('previous_years', '0002_auto_20210223_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricOSCARReturn',
            fields=[
                ('row_number', models.BigIntegerField()),
                ('sub_segment_code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('sub_segment_long_name', models.CharField(max_length=255)),
                ('organization_code', models.CharField(max_length=50)),
                ('organization_alias', models.CharField(max_length=255)),
                ('apr', models.BigIntegerField(default=0)),
                ('may', models.BigIntegerField(default=0)),
                ('jun', models.BigIntegerField(default=0)),
                ('jul', models.BigIntegerField(default=0)),
                ('aug', models.BigIntegerField(default=0)),
                ('sep', models.BigIntegerField(default=0)),
                ('oct', models.BigIntegerField(default=0)),
                ('nov', models.BigIntegerField(default=0)),
                ('dec', models.BigIntegerField(default=0)),
                ('jan', models.BigIntegerField(default=0)),
                ('feb', models.BigIntegerField(default=0)),
                ('mar', models.BigIntegerField(default=0)),
                ('adj1', models.BigIntegerField(default=0)),
                ('adj2', models.BigIntegerField(default=0)),
                ('adj3', models.BigIntegerField(default=0)),
                ('financial_year', models.IntegerField()),
            ],
            options={
                'db_table': 'oscar_return_historicaloscarreturn',
                'ordering': ['sub_segment_code'],
                'managed': False,
            },
        ),

        migrations.RunSQL(
            """
                  DROP VIEW  if exists "oscar_return_historicaloscarreturn";
                  CREATE VIEW "oscar_return_historicaloscarreturn" as 
    
             SELECT row_number() OVER (ORDER BY ss.sub_segment_code) AS row_number,
                m.financial_year_id as financial_year,
                COALESCE(nac."account_L5_code_upload", nac."account_L5_code") AS account_l5_code,
                ss.sub_segment_code,
                ss.sub_segment_long_name,
                ss.organization_code,
                ss.organization_alias,
                round(sum(apr) / 100000) AS apr,
                round(sum(may) / 100000) AS may,
                round(sum(jun) / 100000) AS jun,
                round(sum(jul) / 100000) AS jul,
                round(sum(aug) / 100000) AS aug,
                round(sum(sep) / 100000) AS sep,
                round(sum(oct) / 100000) AS oct,
                round(sum(nov) / 100000) AS nov,
                round(sum("dec") / 100000) AS "dec",
                round(sum(jan) / 100000) AS jan,
                round(sum(feb) / 100000) AS feb,
                round(sum(mar) / 100000) AS mar,
                round(sum(adj1) / 100000) AS adj1,
                round(sum(adj2) / 100000) AS adj2,
                round(sum(adj3) / 100000) AS adj3
               FROM previous_years_archivedforecastdata m
                 JOIN previous_years_archivedfinancialcode ff ON m.financial_code_id = ff.id
                 LEFT JOIN "chartofaccountDIT_archivednaturalcode" nac ON ff.natural_account_code_id = nac.id
                 JOIN costcentre_archivedcostcentre cc ON ff.cost_centre_id = cc.id
                 JOIN "chartofaccountDIT_archivedprogrammecode" p ON ff.programme_id = p.id
                 LEFT JOIN "treasurySS_archivedsubsegment" ss ON cc.treasury_segment_code = ss.segment_code
                       AND p.budget_type_id = ss.dit_budget_type_id
                       AND ss.financial_year_id = m.financial_year_id
              GROUP BY (COALESCE(nac."account_L5_code_upload", nac."account_L5_code")), 
              ss.organization_code, 
              ss.organization_alias, 
              ss.sub_segment_code, 
              m.financial_year_id;
        """,
            'DROP VIEW "oscar_return_historicaloscarreturn";',
        ),

    ]
