name: FFT CI

on:
  pull_request:
  merge_group:

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Create a .env file
        run: cp .env.ci .env

      - name: Install poetry
        run: pip install poetry

      - name: Install python dependencies
        run: poetry install --with dev

      - name: Run ruff
        run: make ruff-check

      - name: Run isort
        run: make isort-check

      - name: Run black
        run: make black-check

      - name: Install React app
        run: npm ci

      - name: Run prettier
        run: make prettier-check

      - name: Build images
        run: make build

      - name: Run containers
        run: make up-detached

      - name: Run makemigrations in check mode
        run: make check-migrations

      - name: Collect static
        run: make collectstatic

      - name: Run tests
        run: make test-ci

      - name: Bring up chrome
        run: docker compose up -d chrome

      - name: Run BDD tests
        run: make bdd

      - name: Docker compose down
        run: docker compose down
