PAYROLL_REPORT_FIELDS: list[tuple[str, str]] = [
    ("first_name", "First Name"),
    ("last_name", "Last Name"),
    ("grade", "Grade Level"),
    ("employee_no", "Staff Number"),
    ("fte", "FTE"),
    ("wmi_payroll", "WMI Payroll"),
    ("cost_centre_id", "CC Acronym"),
    ("cost_centre_name", "CC Name"),
    ("directorate", "Directorate"),
    ("group_name", "Group Name"),
    ("programme_code", "Programme Code"),
    ("assignment_status", "Assignment Status"),
    ("person_type", "Person Type"),
    ("april", "April"),
    ("may", "May"),
    ("june", "June"),
    ("july", "July"),
    ("august", "August"),
    ("september", "September"),
    ("october", "October"),
    ("november", "November"),
    ("december", "December"),
    ("january", "January"),
    ("february", "February"),
    ("march", "March"),
    ("payroll_cost_centre", "Payroll Cost Centre"),
    ("salary", "Salary"),
    ("recruitment_type", "Recruitment Type"),
    ("HR_stage", "HR Stage"),
    ("HR_ref", "HR Ref"),
    ("vacancy_type", "Vacancy Type"),
    ("fte_april", "April FTE"),
    ("fte_may", "May FTE"),
    ("fte_june", "June FTE"),
    ("fte_july", "July FTE"),
    ("fte_august", "August FTE"),
    ("fte_september", "September FTE"),
    ("fte_october", "October FTE"),
    ("fte_november", "November FTE"),
    ("fte_december", "December FTE"),
    ("fte_january", "January FTE"),
    ("fte_february", "February FTE"),
    ("fte_march", "March FTE"),
    ("programme_switch", "Programme Switch"),
    ("capital", "Capital"),
    ("recharge", "Recharge"),
    ("reason", "Reason"),
    ("narrative", "Narrative"),
    ("budget_type", "vw_Dim_UCoA_Programme.Control_Budget"),
    ("fte_total", "FTE total"),
    ("employee_name", "Employee Name"),
    ("cc_name_number", "CC name & number"),
    ("employee_prog_code", "Employee & prog code"),
]
