PAYROLL_REPORT_FIELDS = [
    ("first_name", "First Name"),
    ("last_name", "Last Name"),
    ("grade", "Grade Level"),
    ("employee_no", "Staff Number"),
    ("fte", "FTE"),
    ("wmi_payroll", "WMI Payroll"),
    ("cost_centre_id", "CC Acronym"),
    ("cost_centre_name", "CC Name"),
    ("directorate", "Directorate"),
    ("group_name", "Group Name"),
    ("programme_code", "Programme Code"),
    ("assignment_status", "Assignment Status"),
    ("person_type", "Person Type"),
    ("april", "April"),
    ("may", "May"),
    ("june", "June"),
    ("july", "July"),
    ("august", "August"),
    ("september", "September"),
    ("october", "October"),
    ("november", "November"),
    ("december", "December"),
    ("january", "January"),
    ("february", "February"),
    ("march", "March"),
    ("payroll_cost_centre", "Payroll Cost Centre"),
    ("salary", "Salary"),
    ("recruitment_type", "Recruitment Type"),
    ("HR_stage", "HR Stage"),
    ("HR_ref", "HR Ref"),
    ("vacancy_type", "Vacancy Type"),
    ("fte", "April FTE"),
    ("fte", "May FTE"),
    ("fte", "June FTE"),
    ("fte", "July FTE"),
    ("fte", "August FTE"),
    ("fte", "September FTE"),
    ("fte", "October FTE"),
    ("fte", "November FTE"),
    ("fte", "December FTE"),
    ("fte", "January FTE"),
    ("fte", "February FTE"),
    ("fte", "March FTE"),
    ("programme_switch", "Programme Switch"),
    ("capital", "Capital"),
    ("recharge", "Recharge"),
    ("reason", "Reason"),
    ("narrative", "Narrative"),
    ("budget_type", "vw_Dim_UCoA_Programme.Control_Budget"),
    ("fte_total", "FTE total"),
    ("employee_name", "Employee Name"),
    ("cc_name_number", "CC name & number"),
    ("employee_prog_code", "Employee & prog code"),
]
