# Generated by Django 3.0.14 on 2021-04-30 09:25

from django.db import migrations, models
import django_chunk_upload_handlers.clam_av


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_auto_20200820_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='s3_document_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='', validators=[django_chunk_upload_handlers.clam_av.validate_virus_check_result]),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='s3_document_file',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django_chunk_upload_handlers.clam_av.validate_virus_check_result]),
        ),
    ]
