# Generated by Django 3.2.16 on 2023-04-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0004_auto_20211209_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='document_type',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget'), ('previousyear', 'Previous Year'), ('projectpercentage', 'Project Percentages'), {'forecast', 'Forecast'}, {'Other', 'other'}], default='actuals', max_length=100),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_location',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget'), ('previousyear', 'Previous Year'), ('projectpercentage', 'Project Percentages'), {'forecast', 'Forecast'}, {'Other', 'other'}], default='S3', max_length=100),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='document_type',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget'), ('previousyear', 'Previous Year'), ('projectpercentage', 'Project Percentages'), {'forecast', 'Forecast'}, {'Other', 'other'}], default='actuals', max_length=100),
        ),
        migrations.AlterField(
            model_name='simplehistoryfileupload',
            name='file_location',
            field=models.CharField(choices=[('actuals', 'Actuals'), ('budget', 'Budget'), ('previousyear', 'Previous Year'), ('projectpercentage', 'Project Percentages'), {'forecast', 'Forecast'}, {'Other', 'other'}], default='S3', max_length=100),
        ),
    ]
