# Generated by Django 5.1.3 on 2024-12-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_file", "0006_alter_simplehistoryfileupload_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileupload",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("actuals", "Actuals"),
                    ("budget", "Budget"),
                    ("previousyear", "Previous Year"),
                    ("projectpercentage", "Project Percentages"),
                    ("forecast", "Forecast"),
                    ("other", "Other"),
                ],
                default="actuals",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="fileupload",
            name="file_location",
            field=models.CharField(
                choices=[
                    ("actuals", "Actuals"),
                    ("budget", "Budget"),
                    ("previousyear", "Previous Year"),
                    ("projectpercentage", "Project Percentages"),
                    ("forecast", "Forecast"),
                    ("other", "Other"),
                ],
                default="S3",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="simplehistoryfileupload",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("actuals", "Actuals"),
                    ("budget", "Budget"),
                    ("previousyear", "Previous Year"),
                    ("projectpercentage", "Project Percentages"),
                    ("forecast", "Forecast"),
                    ("other", "Other"),
                ],
                default="actuals",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="simplehistoryfileupload",
            name="file_location",
            field=models.CharField(
                choices=[
                    ("actuals", "Actuals"),
                    ("budget", "Budget"),
                    ("previousyear", "Previous Year"),
                    ("projectpercentage", "Project Percentages"),
                    ("forecast", "Forecast"),
                    ("other", "Other"),
                ],
                default="S3",
                max_length=100,
            ),
        ),
    ]
